title: ✴ STYLE

form:
  validation: loose
  fields:

    columns:
      type: columns
      fields:

        _color:
          type: column
          fields:

            color.key.hue:
              type: range
              label: Key Hue
              help: 0 - 359
              default: 44
              validate:
                min: 0
                max: 359

            color.1.hueOffset:
              type: range
              label: Color 1 Hue offset
              help: degree offset from key color
              default: -150
              validate:
                min: -359
                max: 359

            color.2.hueOffset:
              type: range
              label: Color 2 Hue offset
              help: degree offset from key color
              default: 120
              validate:
                min: -359
                max: 359

            color.saturation:
              type: range
              label: initial color saturation in percent
              help: 0 - 100
              default: 30
              validate:
                min: 0
                max: 100

            color.lightness.lighter:
              type: range
              label: highest lightness offset
              help: 0 - 100
              default: 90
              validate:
                min: 0
                max: 100

            color.lightness.light:
              type: range
              label: high lightness offset
              help: 0 - 100
              default: 70
              validate:
                min: 0
                max: 100

            color.lightness.mid:
              type: range
              label: mid lightness offset
              help: 0 - 100
              default: 50
              validate:
                min: 0
                max: 100

            color.lightness.dark:
              type: range
              label: low lightness offset
              help: 0 - 100
              default: 30
              validate:
                min: 0
                max: 100

            color.lightness.darker:
              type: range
              label: lowest lightness offset
              help: 0 - 100
              default: 10
              validate:
                min: 0
                max: 100

            color.foreground:
              type: text
              label: Foreground Color
              default: "#333"

            color.background:
              type: text
              label: Background Color
              default: "#CCC"


        _fonts:
          type: column
          fields:

            _fonts_section:
              type: section
              title: Fonts
              underline: true

              fields:

                font:
                  type: select
                  label: Font
                  classes: fancy
                  style: vertical
                  default: 'Lato'
                  config-options@: fonts


                font_display:
                  type: select
                  label: Display Font
                  classes: fancy
                  style: vertical
                  default: 'Lato'
                  config-options@: fonts

                font_code:
                  type: text
                  label: Code Font
                  style: vertical
                  default: monospace

            _sizes:
              type: section
              title: Sizes
              underline: true

              fields:

                header_height:
                  type: text
                  label: Header Height
                  style: vertical
                  default: 9em

                fitz:
                  type: text
                  label: Fitz
                  help: incremental measure for general margin and padding
                  style: vertical
                  default: .5em

                col:
                  type: text
                  label: Column
                  help: incremental measure for general column
                  style: vertical
                  default: 18em
